### ISSUE TITLE
Compatible boards

### ISSUE THREAD

**Issue by wormscoffer** [kuashio/RISC-V-intro-course#1]
Hello

I can't seem to purchase the board mentioned in this course.

Are there alternatives that would be suitable and are available to purchase?

Thanks

**Comment by wormscoffer** [comment]
Hmmmm....not regularly checked it seems.

**Comment by kuashio** [comment]
Indeed. Apologies.
Is a board mentioned in the course? The one showcased in the exercise files is a simulated model, which I don’t think is physically available.

As for RISC-V microcontroller boards, I recommend both Red-V Thing boards by Sparkfun, and the SeeedStudio GD32 RISC-V Dev Board. That said, all those have been scarce since COVID :/

**Comment by wormscoffer** [comment]
Thanks.

I started on the Udemy course where you recommend the GD32 and that still seems to be harder to find than hen's teeth. I'll see if I can find a Red-V.

Any others that would suffice for the course? I have a Milk Duo.

TIA

Andrew

**Comment by wormscoffer** [comment]
I managed to find a Sparkfun RED-V as a bundle from Eureka Leap.
